### ISSUE TITLE
Create entity

### ISSUE THREAD

**Issue by Manikanta05** [Manikanta05/Hacktoberfest2022#3]
Create an entity class within the model package.
Entity class must contain the following as private attributes: id,title,description,created_on,updated_on with suitable datatypes.
Ensure you create getters, setters, and constructors.

**Comment by iremugurlu** [comment]
Hey, I'm interested. Can you assign this one to me?

**Comment by Manikanta05** [comment]
Hey @iremugurlu You can start working on it!
Happy Hacking:)

**Comment by iremugurlu** [comment]
Hi @Manikanta05, I am not able to create a pull request. Apparently, I don't have write access to the repo. Could you allow that?

**Comment by Manikanta05** [comment]
You've to create pull request, according to hacktoberfest guidelines no collaborator access will be given.

**Comment by iremugurlu** [comment]
Clear, thanks. I've created a pull request from fork 👍
